#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SenseoBT.Resource", IsApplication=true)]

namespace SenseoBT
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bt = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btnoff = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btnon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btred = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cup1off = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int cup1on = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int cup2off = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int cup2on = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int monoandroidsplash = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int thermometre = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int thermometreon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int wateroff = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int wateron = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int btnCUP1 = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int btnCUP2 = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int btnONOFF = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int icon = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int lvLog = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
